<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>0.0.0.1</Version>
    <Author>Aireil</Author>
    <Name>InputFlow</Name>
    <Punchline>Improve the native text inputs by restoring common text-editing behaviors.</Punchline>
    <Description>Supported shortcuts:
        - CTRL + CTRL + LEFT/RIGHT to jump words
        - CTRL + SHIFT + LEFT/RIGHT to select words
        - CTRL + BACK/DELETE to delete words
        - CTRL/SHIFT + INSERT to copy/paste
        - SHIFT + DELETE to cut
    Changes:
        - LEFT/RIGHT unselects even if the cursor is at the start/end respectively
        - LEFT/RIGHT with an active selection unselects and puts the cursor at the beginning/end of the selection
    </Description>
    <RepoUrl>https://github.com/Aireil/InputFlow</RepoUrl>
    <Tags>text;input;shortcut;ctrl;shift</Tags>
  </PropertyGroup>
</Project>
